# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI and Build with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pi6/pom.xml
      
    - name: Add artifacts to publish to the temp folder
      run: |
          mkdir downloads
          mv pi6/target/* downloads
          cd downloads
          cd ..
    
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
          name: assets
          path: downloads
